//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mashinin.Resources.Localization.SharedResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class az {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal az() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mashinin.Resources.Localization.SharedResource.az", typeof(az).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NameAz=&quot;{0}&quot;, və ya NameRu=&quot;{1}&quot;, və ya NameEn=&quot;{2}&quot;, və ya Index=&quot;{3}&quot; olan şəhər mövcuddur..
        /// </summary>
        public static string cityExists {
            get {
                return ResourceManager.GetString("cityExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şəhər tapılmadı..
        /// </summary>
        public static string cityNotFound {
            get {
                return ResourceManager.GetString("cityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NameAz=&quot;{0}&quot;, və ya NameRu=&quot;{1}&quot;, və ya NameEn=&quot;{2}&quot;, və ya HexCode=&quot;{3}&quot; olan rənq mövcuddur..
        /// </summary>
        public static string colorExists {
            get {
                return ResourceManager.GetString("colorExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rənq tapılmadı..
        /// </summary>
        public static string colorNotFound {
            get {
                return ResourceManager.GetString("colorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HexCode lazım olan formata uyğun deyil..
        /// </summary>
        public static string hexCodeNotMatchFormat {
            get {
                return ResourceManager.GetString("hexCodeNotMatchFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adı &quot;{0}&quot; və ya TurboAzId=&quot;{1}&quot; olan marka mövcuddur..
        /// </summary>
        public static string makeExists {
            get {
                return ResourceManager.GetString("makeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marka tapılmadı..
        /// </summary>
        public static string makeNotFound {
            get {
                return ResourceManager.GetString("makeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adı &quot;{0}&quot;, və ya TurboAzId=&quot;{1}&quot;, və ya MakeId=&quot;{2}&quot; olan model mövcuddur..
        /// </summary>
        public static string modelExists {
            get {
                return ResourceManager.GetString("modelExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model tapılmadı..
        /// </summary>
        public static string modelNotFound {
            get {
                return ResourceManager.GetString("modelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad mütləqdir!.
        /// </summary>
        public static string nameRequired {
            get {
                return ResourceManager.GetString("nameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Göndərilən obyekt boşdur..
        /// </summary>
        public static string objectIsNull {
            get {
                return ResourceManager.GetString("objectIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mütləqdir!.
        /// </summary>
        public static string required {
            get {
                return ResourceManager.GetString("required", resourceCulture);
            }
        }
    }
}
