//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mashinin.Resources.Localization.SharedResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mashinin.Resources.Localization.SharedResource.en", typeof(en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City exists with NameAz=&quot;{0}&quot;, or NameRu=&quot;{1}&quot;, or NameEn=&quot;{2}&quot;, or Index=&quot;{3}&quot;..
        /// </summary>
        public static string cityExists {
            get {
                return ResourceManager.GetString("cityExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City is not found..
        /// </summary>
        public static string cityNotFound {
            get {
                return ResourceManager.GetString("cityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color exists with NameAz=&quot;{0}&quot;, or NameRu=&quot;{1}&quot;, or NameEn=&quot;{2}&quot;, or HexCode=&quot;{3}&quot;..
        /// </summary>
        public static string colorExists {
            get {
                return ResourceManager.GetString("colorExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color is not found..
        /// </summary>
        public static string colorNotFound {
            get {
                return ResourceManager.GetString("colorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid hex color code format..
        /// </summary>
        public static string hexCodeNotMatchFormat {
            get {
                return ResourceManager.GetString("hexCodeNotMatchFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make exists with Name=&quot;{0}&quot; or TurboAzId=&quot;{1}&quot;..
        /// </summary>
        public static string makeExists {
            get {
                return ResourceManager.GetString("makeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make is not found..
        /// </summary>
        public static string makeNotFound {
            get {
                return ResourceManager.GetString("makeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model exists with Name=&quot;{0}&quot;, or TurboAzId=&quot;{1}&quot;, or MakeId=&quot;{2}&quot;..
        /// </summary>
        public static string modelExists {
            get {
                return ResourceManager.GetString("modelExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model is not found..
        /// </summary>
        public static string modelNotFound {
            get {
                return ResourceManager.GetString("modelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required!.
        /// </summary>
        public static string nameRequired {
            get {
                return ResourceManager.GetString("nameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent object is null..
        /// </summary>
        public static string objectIsNull {
            get {
                return ResourceManager.GetString("objectIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is required!.
        /// </summary>
        public static string required {
            get {
                return ResourceManager.GetString("required", resourceCulture);
            }
        }
    }
}
